export {default as Button } from "./button"
export {default as Title } from "./Title"
export {default as Card } from "./Card"
export {default as Slider } from "./Slider"
export {default as Protsent } from "./Protsent"
export {default as Describtion } from "./Describtion"